### PR TITLE
Add option for jitter, fix wording of randdelay

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by leahneukirchen** [comment]
The docs for `-J` should mention this is choosen randomly.

Using auxval twice is not a good idea in my opinion. Unfortunately the platforms I target can not decide whether to provide getentropy or getrandom (or both).

**Comment by abenson** [comment]
Why not just srand48/lrand48?

**Comment by leahneukirchen** [comment]
Yeah, but which seed?

**Comment by abenson** [comment]
The existing `getpid() ^ start` seems reasonable for the application, unless I'm missing something.

**Comment by leahneukirchen** [comment]
Yeah, ok.

**Pull request merged**
